apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ickqq8ptc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ickqq8ptc-nodejs 
  name: ickqq8ptc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ickqq8ptc-nodejs 
